apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocker-fetcher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocker-fetcher
  template:
    metadata:
      labels:
        app: blocker-fetcher
    spec:
      containers:
        - image: docker.io/sr123/fetcher:fetcher-1.0.0-SNAPSHOT-2.1
          name: blocker-fetcher
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: gcloud
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://34.89.142.186:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://34.89.142.186:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://35.240.79.227:8083
            #- name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            #  value: jdbc:postgresql://34.89.221.63:5432/postgres
            #- name: KUMULUZEE_DATASOURCES0_USERNAME
            #  value: postgres
            #- name: KUMULUZEE_DATASOURCES0_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #     name: pg-pass
            #     key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /fetcher/health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /fetcher/health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: blocker-fetcher
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: blocker-fetcher