apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocker-provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocker-provider
  template:
    metadata:
      labels:
        app: blocker-provider
    spec:
      containers:
        - image: docker.io/sr123/provider:provider-1.0.0-SNAPSHOT-8.1
          name: blocker-provider
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: gcloud
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://35.240.79.227:8080
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://34.89.221.63:5432/postgres
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: blocker-provider
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: blocker-provider