kumuluzee:
  name: provider
  env:
    name: test
  version: 1.0.0
  server:
    http:
      port: 8081
  #datasources:
  #  - jndi-name: jdbc/ImageMetadataDS
  #    connection-url: jdbc:postgresql://192.168.29.109:5432/image-metadata
  #    username: dbuser
  #    password: postgres
  #    max-pool-size: 20
  discovery:
    etcd:
      hosts: http://34.89.142.186:2379/
  health:
    servlet:
      mapping: /provider/health
      enabled: true
    logs:
      enabled: true
    checks:
      etcd-health-check:
        connection-url: http://34.89.142.186:2379/health
  metrics:
    web-instrumentation:
      - name: provider-api
        url-pattern: /provider/api/*
  logs:
    loggers:
      - name: com.kumuluz.ee.blocker.provider.api.ProviderApi
        level: INFO
      - name: ''
        level: INFO
configuration-properties:
  provider:
    enabled: true