kumuluzee:
  name: provider
  env:
    name: test
  version: 1.0.0
  server:
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/blockerstorage
      connection-url: jdbc:postgresql://34.65.73.233/blockerstorage
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://34.65.200.108:2379/
  health:
    servlet:
      mapping: /provider/health
      enabled: true
    logs:
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/blockerstorage
      etcd-health-check:
        connection-url: http://34.65.200.108:2379/health
  metrics:
    web-instrumentation:
      - name: provider-api
        url-pattern: /provider/api/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="trace">
                                      <AppenderRef ref="console" level="info"/>
                                  </Root>
                              </Loggers>
                          </Configuration>'
configuration-properties:
  provider:
    enabled: true